import json
from openai import OpenAI
openai_client = OpenAI()


# --------------------------------
# Tool
# --------------------------------
def get_order_status(order_id: str) -> dict:
    orders = {
        "1234": {
            "status": "Shipped",
            "location": "Dhaka",
            "expected_delivery": "September 22, 2026"
        },
        "5678": {
            "status": "Delivered",
            "location": "Chittagong",
            "expected_delivery": "September 18, 2026"
        }
    }


    return orders.get(
        order_id,
        {"status": "Order not found"}
    )


# Describe the tool to the model
available_tools = [
    {
        "type": "function",
        "name": "get_order_status",
        "description": "Get the current status of a customer's order.",
        "parameters": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string",
                    "description": "The customer's order ID."
                }
            },
            "required": ["order_id"],
            "additionalProperties": False
        },
        "strict": True
    }
]


# --------------------------------
# Agent
# --------------------------------
def process_user_request(user_request: str) -> None:
    # Ask the model to process the user's request
    llm_response = openai_client.responses.create(
        model="gpt-5.6",
        input=user_request,
        tools=available_tools
    )
    # Inspect the model's output
    for output_item in llm_response.output:
        if output_item.type == "function_call":
            print("Agent requested tool:")
            print(f"  Tool: {output_item.name}")
            print(f"  Arguments: {output_item.arguments}")


            # Parse the arguments generated by the model
            tool_arguments = json.loads(output_item.arguments)


            # Execute the actual Python function
            tool_result = get_order_status(
                tool_arguments["order_id"]
            )


            print("Tool result:")
            print(tool_result)
            # Send the tool result back to the model
            final_response = openai_client.responses.create(
                model="gpt-5.6",
                input=[
                    {
                        "type": "function_call_output",
                        "call_id": output_item.call_id,
                        "output": json.dumps(tool_result)
                    }
                ],
                previous_response_id=llm_response.id
            )


            print("\nAgent response:")
            print(final_response.output_text)
            return


    # If no tool was required
    print("Agent response:")
    print(llm_response.output_text)


# --------------------------------
# Application Entry Point
# --------------------------------


def main() -> None:


    #user_request = "Where is my order #1234?"
    #user_request = "Where is my order #8878?"
    user_request = "What is the capital of France?"
    process_user_request(user_request)


if __name__ == "__main__":
    main()
